kafka.topic.name: data-topic
kafka.topic.servers: kafka-dev-kafka-bootstrap.kafka-dev:9092
server.port: 8080
spring.kafka.bootstrap-servers: kafka-dev-kafka-bootstrap.kafka-dev:9092
spring.kafka.properties.sasl.mechanism: SCRAM-SHA-512 
spring.kafka.properties.security.protocol: SASL_SSL
spring.kafka.properties.ssl.truststore.location: /truststore/truststore.jks

#spring.kafka.properties.sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="@@username@@" password="@@password@@";
#spring.kafka.properties.ssl.truststore.password: @@JKS_PASSWORD@@

spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer: io.apicurio.registry.utils.serde.AvroKafkaSerializer
spring.kafka.producer.properties.apicurio.registry.url: http://registry-service.kafka-registry:8080/api
spring.kafka.producer.properties.apicurio.registry.artifact-id: io.apicurio.registry.utils.serde.strategy.TopicIdStrategy
spring.kafka.producer.properties.apicurio.registry.global-id: io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy